name: Build image and automatically push to Docker Hub 
on: 
    push:
        branches:
            - sept20
jobs:
    deployment: 
        runs-on: ubuntu-latest
        steps: 
            - name: "Checkouts of the repository"
              uses: actions/checkout@v4
        
            - name: "Build the image"
              run: |
                sudo docker build -t theoafactor/testbooksfinder:latest .

            - name: "Push to Docker Hub"
              run: |
                sudo docker push theoafactor theoafactor/testbooksfinder:latest

            - name: "Test Okay"
              run: |
                echo "Everything works fine"
                